CrowdTouring Projeto/Controllers/SolucoesController.cs
using CrowdTouring_Projeto.Models;
using CrowdTouring_Projeto.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrowdTouring_Projeto.Controllers
{
    public class SolucoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Solucoes
        public ActionResult Index()
        {
            return View();
        }

        // GET: Solucoes/Details/5
        public ActionResult Details(int id)
        {
            var solucao = db.Solucoes.Where(a => a.SolucaoId == id).First();
            var anexo = db.Anexos.Where(a => a.SolucaoId == id).First();
            SolucaoDesafio Solucao = new SolucaoDesafio();
            Solucao.NomeSolucao = solucao.SolucaoTitulo;
            Solucao.DescricaoSolucao = solucao.Descricao;
            Solucao.FileId = anexo.AnexoId;
            Solucao.FileName = anexo.NomeFicheiro;
            Solucao.FilePath = anexo.Caminho;
            if(solucao.User.Id != User.Identity.GetUserId())
            {
                solucao.NumeroVisualizacoes++;
                db.SaveChanges();
            }

            return View(Solucao);
        }

        // GET: Solucoes/Create
        public ActionResult Create(int DesafioId)
        {
            var desafio = db.Desafios.Where(d => d.DesafioId == DesafioId).First();
            var SolucaoDesafio = new SolucaoDesafio();
            SolucaoDesafio.IdDesafio = desafio.DesafioId;
            SolucaoDesafio.NomeDesafio = desafio.TipoTrabalho;
            return View(SolucaoDesafio);
        }

        // POST: Solucoes/Create
        [HttpPost]
        public ActionResult Create(SolucaoDesafio SolucaoDesafio,HttpPostedFileBase file)
        {

            string extensao = Path.GetExtension(file.FileName);
            if (file == null)
            {
                ModelState.AddModelError("ErroFicheiro2", "Tem que Submeter pelo menos um ficheiro");
            }

            if (file != null)
            {
                int indexOf = file.ContentType.IndexOf("zip");
                if (extensao != ".zip")
                {
                    ModelState.AddModelError("Zip2", "Compacte os ficheiros e envie em formato .Zip");
                }
            }

            if (ModelState.IsValid)
            {
                var Solucao = new Solucao();
                Solucao.DesafioId = SolucaoDesafio.IdDesafio;
                Solucao.Descricao = SolucaoDesafio.DescricaoSolucao;
                Solucao.SolucaoTitulo = SolucaoDesafio.NomeSolucao;
                Solucao.ApplicationUserId = User.Identity.GetUserId();
                Solucao.DataCriacao = DateTime.Now;
                db.Solucoes.Add(Solucao);

                db.SaveChanges();

                #pragma warning disable CS0162 // Unreachable code detected
                if (file.ContentLength > 0)
                {
                    Anexo anexo = new Anexo();

                    string filePath = Path.Combine(HttpContext.Server.MapPath("~/Anexos/"),
                                                   Path.GetFileName(file.FileName));
                    file.SaveAs(filePath);
                    anexo.Caminho = filePath;
                    anexo.SolucaoId = Solucao.SolucaoId;
                    anexo.NomeFicheiro = file.FileName;
                    db.Anexos.Add(anexo);

                    db.SaveChanges();

                    return RedirectToAction("Details", "Desafios", new { id = SolucaoDesafio.IdDesafio });
                }
            }
            return View(SolucaoDesafio);
        }

        public ActionResult Votacao(int id, int avaliacao)
        {
            var solucao = db.Solucoes.Where(d => d.SolucaoId == id).FirstOrDefault();
            solucao.NumeroVotos = solucao.NumeroVotos + avaliacao;
            Voto voto = new Voto();
            voto.solucao = solucao;
            voto.userId = User.Identity.GetUserId();
            db.Votos.Add(voto);
            db.SaveChanges();
            solucao.Votos.Add(voto);
            db.SaveChanges();
            return RedirectToAction("Details", "Desafios",new { @id = solucao.DesafioId});
        }

        // GET: Solucoes/Edit/5
        public ActionResult Edit(int id)
        {
            var solucao = db.Solucoes.Where(s => s.SolucaoId == id).First();
            var anexo = db.Anexos.Where(s => s.SolucaoId == id).FirstOrDefault();
            SolucaoDesafio solucaoDesafio = new SolucaoDesafio();
            solucaoDesafio.NomeSolucao = solucao.SolucaoTitulo;
            solucaoDesafio.DescricaoSolucao = solucao.Descricao;
            solucaoDesafio.FileName = anexo.NomeFicheiro;
            solucaoDesafio.IdSolucao = id;
            solucaoDesafio.IdDesafio = solucao.DesafioId;
            return View(solucaoDesafio);
        }

        // POST: Solucoes/Edit/5
        [HttpPost]
        public ActionResult Edit(SolucaoDesafio solucaoDesafio, HttpPostedFileBase file)
        {
            var solucao = db.Solucoes.Where(s => s.SolucaoId == solucaoDesafio.IdSolucao).First();
            var anexo = db.Anexos.Where(s => s.SolucaoId == solucaoDesafio.IdSolucao).First();
            try
            {
                solucao.SolucaoTitulo = solucaoDesafio.NomeSolucao;
                solucao.Descricao = solucaoDesafio.DescricaoSolucao;              
                if(file.ContentLength > 0)
                {
                    anexo.Caminho = solucaoDesafio.FilePath;
                    anexo.SolucaoId = solucaoDesafio.IdSolucao;
                    anexo.NomeFicheiro = file.FileName;
                }
                db.SaveChanges();
                return RedirectToAction("Details","Desafios", new { id = solucaoDesafio.IdDesafio });
            }
            catch
            {
                return RedirectToAction("Details", "Desafios", new { id = solucaoDesafio.IdDesafio });
            }
        }

        // GET: Solucoes/Delete/5
        public ActionResult Eliminar(int id,int desafio)
        {
            Solucao solucao = db.Solucoes.Find(id);
            var desafioQ = db.Votos.RemoveRange(db.Votos.Where(d => d.solucao.SolucaoId == id));
            db.SaveChanges();
            db.Solucoes.Remove(solucao);
            db.SaveChanges();
            return RedirectToAction("Details", "Desafios", new { id = solucao.DesafioId });
        }

        public ActionResult EstrelasAvaliacao(int estrela,int id)
        {
            var solucao = db.Solucoes.Where(m => m.SolucaoId == id).FirstOrDefault();
            var userId = User.Identity.GetUserId();
            var estrelasDados = db.Estrelas.Where(m => m.User == userId).FirstOrDefault();
            Estrela Estrela = new Estrela();
            Estrela.solucao = solucao;
            Estrela.User = User.Identity.GetUserId();
            Estrela.EstrelaValor = estrela;

            if (estrelasDados == null)
            {
                db.Estrelas.Add(Estrela);
                db.SaveChanges();
                solucao.Estrelas.Add(Estrela);
                db.SaveChanges();
            }
            else
            {
                estrelasDados.EstrelaValor = estrela;
                Estrela novaEstrela = solucao.Estrelas.Where(m => m.User == userId).First();
                novaEstrela.EstrelaValor = estrela;
                db.SaveChanges();
               
            }

            return RedirectToAction("Details", "Desafios", new { @id = solucao.DesafioId });
        }

        public ActionResult Vencedor (int id,int id2)
        {
            var desafio = db.Desafios.Where(d => d.DesafioId == id2).First();
            desafio.IdSolucaoVencedora = id;
            db.SaveChanges();
            return RedirectToAction("Index", "desafios");
        }

        // POST: Solucoes/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CrowdTouring Projeto/Views/Solucoes/Create.cshtml
@model CrowdTouring_Projeto.ViewModel.SolucaoDesafio
@{
    ViewBag.Title = "Create";
}

<div class="col-md-offset-1 col-md-9" style="background-color:#f7c36d;margin-top:40px;border-radius:9px">

    @using (Html.BeginForm("Create", "Solucoes", FormMethod.Post, new { @class = "form form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <h4 style="text-align:left;margin-left:145px">Desafio - @Model.NomeDesafio</h4>
        @Html.HiddenFor(m => m.NomeDesafio)
        <div class="form-group" style="margin-top:40px">
            @Html.LabelFor(m => m.NomeSolucao, "Solução", new { @class = "col-md-2 control-label"})
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.NomeSolucao, "Solucao", new { @class = "form-control", maxlength = 50, @id = "TituloSolucao", autocomplete = "off" })
                <div id="caracteres"></div>
                @Html.ValidationMessageFor(m => m.NomeSolucao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.DescricaoSolucao, "Descrição", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.DescricaoSolucao, 10, 25, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DescricaoSolucao, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(m => m.IdDesafio)
        <div class="form-group" style="margin-left:150px">
            <input type="file" name="file" class="marginTop" />
            @Html.ValidationMessage("ErroFicheiro2", new { @class = "text-danger" })
            @Html.ValidationMessage("Zip2", new { @class = "text-danger" })
        </div>

        <div class="col-md-offset-2 col-md-10" style="margin-top:20px">
            <textarea rows="8" cols="80" class="form-control" disabled>Como cliente:após o seu desafio ser resolvido, este compromete-se a efetuar o pagamento ao resolvedor que apresentou a proposta de solução vencedora. A Plataforma não se responsabiliza pelo incumprimento dos pagamentos, desta forma é necessário haver comunicação entre o cliente e o resolvedor de forma a existir consenso das duas partes.
                                                    Como resolvedor:compromete-se a cumprir os prazos estipulados por cada cliente e declara que todos os tipos de propostas de solução submetidas são de autoria própria, que tem a propriedade intelectual e/ou o poder legal de transmitir ilimitadamente a totalidade dos direitos, de forma exclusiva e perpétua, não havendo lugar a royalties ou pagamentos adicionais, para além do pagamento estabelecido no prémio definido no desafio. Situações de plágio e de apropriação de conteúdos e/ou ideias, projetos de outros autores são expressamente proibidas.
                                                    Como avaliador:compromete-se a avaliar as propostas de solução de forma justa de modo a facilitar ao cliente eleger a proposta de solução vencedora.
            </textarea>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <label>@Html.CheckBox("termos", false) Li e concordo com os termos de uso da criação da solução </label>
                </div>
            </div>
        </div>

        <div class="row">
            <button id="submeterSolucao" disabled type="submit" class="btn btn-success" style="margin-top:60px;margin-left:165px">Criar Solução</button>
        </div>
        <br/>
    }
    </div>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
var text_max = 50;
$('#caracteres').html(text_max + ' characters restantes');

$('#TituloSolucao').keyup(function () {
var text_length = $('#TituloSolucao').val().length;
var text_remaining = text_max - text_length;

$('#caracteres').html(text_remaining + ' caracteres restantes ');
});

$("#termos").click(function () {
    $("#submeterSolucao").attr("disabled", !this.checked);
});
</script>

   


CrowdTouring Projeto/Views/Solucoes/Details.cshtml
@model CrowdTouring_Projeto.ViewModel.SolucaoDesafio
@{
    ViewBag.Title = "Details";
}

    <div class="modal-dialog" id="myModal">
        <div class="modal-content" style="background-color:#FFFF99">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                </button> <h4 class="modal-title">@Model.NomeSolucao</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-2">
                        <label>Descricao</label>
                    </div>
                </div>
                <div class="row">
                   <p style="margin-left:15px">@Model.DescricaoSolucao</p>
                </div>
                <div class="row" style="margin-top:40px">
                    <div class="col-md-2">
                        <img src="~/StaticImages/ZIP.png" style="width:100px;height:100px" />
                    </div>
                </div>
                <div class="col-md-8">
                    @Html.ActionLink("Download", "Download", "Desafios", new { id = Model.FileId })
                    <span style="display:inline">@Model.FileName</span>
                </div>
            </div>
            <div class="modal-footer">
                
            </div>
        </div>
    </div>

@Scripts.Render("~/bundles/jquery")
<script>
    $('#myModal').on('hidden.bs.modal', function () {
        location.reload();
    });
</script>

CrowdTouring Projeto/Views/Solucoes/Edit.cshtml
@model CrowdTouring_Projeto.ViewModel.SolucaoDesafio

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Solução</h2>

@using (Html.BeginForm("Edit", "Solucoes", FormMethod.Post, new { @class = "form form-horizontal", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Solucao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdSolucao)
        @Html.HiddenFor(model => model.IdDesafio)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeSolucao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeSolucao, "Solução", new { htmlAttributes = new { @class = "form-control",maxlength = 50, @id = "TituloSolucao" } })
                @Html.ValidationMessageFor(model => model.NomeSolucao,"", new { @class = "text-danger" })
                <div id="caracteres"></div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescricaoSolucao, "Descrição Solução", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescricaoSolucao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescricaoSolucao,"", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row" style="margin-top:40px">
            <div class="col-md-offset-2 col-md-2">
                <img src="~/StaticImages/ZIP.png" style="width:100px;height:100px" />
            </div>
        </div>
        <div class="row">
            <div style="margin-left:230px">
                <p>@Model.FileName</p>
            </div>
        </div>
        <div class="row" style="margin-top:40px">
             <div class="col-md-offset-2 col-md-2">
                 <input type="file" name="file" />
             </div>
        </div>
        @Html.HiddenFor(m => m.FileName)
        <div class="form-group" style="margin-top:20px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar alterações" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
var text_max = 50;
$('#caracteres').html(text_max + ' characters restantes');

$('#TituloSolucao').keyup(function () {
var text_length = $('#TituloSolucao').val().length;
var text_remaining = text_max - text_length;

$('#caracteres').html(text_remaining + ' caracteres restantes ');
});

$("#termos").click(function () {
    $("#submeterSolucao").attr("disabled", !this.checked);
});
</script>