CrowdTouring Projeto/Models/Desafio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrowdTouring_Projeto.Models
{
    public class Desafio
    {
   
        public int DesafioId { get; set; }
        [Required]
        public string TipoTrabalho { get; set; }

        public virtual ApplicationUser User { get; set; }

        public string ApplicationUserId { get; set; }
        [Required]
        public string Descricao { get; set; }
        public int TipoAvaliacaoId { get; set; }
        public virtual TipoAvaliacao TipoAvaliacao { get; set; }
        [Range(1, 1000)]
        public int valor { get; set; }
        public int Visualizacoes { get; set; }
        public DateTime DataCriacao { get; set; }
        public double lat { get; set; }
        public double lon { get; set; }
        public int IdSolucaoVencedora { get; set; }
        [Required]
        //[CustomDateRange(ErrorMessage = "tem que estar entre {0} e {1}")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{MMMM/d/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DataFinalSolucoes { get; set; }
        public double DiasAvaliacao { get; set; }
        public double DiasVotacao { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Solucao> Solucao { get; set; }
        public int Pontos { get; set; }

    }

}

CrowdTouring Projeto/Controllers/DesafiosController.cs
using CrowdTouring_Projeto.ViewModel;
using Ionic.Zip;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CrowdTouring_Projeto.Models
{
    public class DesafiosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Desafios
        [Authorize]
        public ActionResult Index()
        {       
            var desafios = db.Desafios.Include(d => d.TipoAvaliacao).Include(d => d.User).Include(d => d.Tags).OrderByDescending(d => d.DataCriacao).Where(d => d.TipoAvaliacaoId == 1);
            var count = db.Desafios.Count();
            carregaInformacaoUtilizador();
            carregaRecentes(desafios,count);
            carregaFiltros();
            verificaAlteraEstadoDesafio(desafios);


            return View(desafios.ToList());
        }

        [Authorize]
        public ActionResult AceitacaoSolucoes()
        {
            var desafios = db.Desafios.Include(d => d.TipoAvaliacao).Include(d => d.User).Include(d => d.Tags).OrderByDescending(d => d.DataCriacao);
            var count = db.Desafios.Count();
            carregaInformacaoUtilizador();
            carregaRecentes(desafios, count);
            var desafios2 = db.Desafios.Include(d => d.TipoAvaliacao).Include(d => d.User).Include(d => d.Tags).OrderByDescending(d => d.DataCriacao).Where(d => d.TipoAvaliacao.TipoAvaliacaoId == 1);
            carregaFiltros();
            verificaAlteraEstadoDesafio(desafios);


            return View("Index", desafios2.ToList());
        }

        [Authorize]
        public ActionResult FechadoVotacao()
        {
            var desafios = db.Desafios.Include(d => d.TipoAvaliacao).Include(d => d.User).Include(d => d.Tags).OrderByDescending(d => d.DataCriacao);
            var count = db.Desafios.Count();
            carregaInformacaoUtilizador();
            carregaRecentes(desafios, count);
            var desafios2 = db.Desafios.Include(d => d.TipoAvaliacao).Include(d => d.User).Include(d => d.Tags).OrderByDescending(d => d.DataCriacao).Where(d => d.TipoAvaliacao.TipoAvaliacaoId == 2);
            carregaFiltros();
            verificaAlteraEstadoDesafio(desafios);


            return View("Index", desafios2.ToList());
        }

        [Authorize]
        public ActionResult FechadoAvaliacao()
        {
            var desafios = db.Desafios.Include(d => d.TipoAvaliacao).Include(d => d.User).Include(d => d.Tags).OrderByDescending(d => d.DataCriacao);
            var count = db.Desafios.Count();
            carregaInformacaoUtilizador();
            carregaRecentes(desafios, count);
            var desafios2 = db.Desafios.Include(d => d.TipoAvaliacao).Include(d => d.User).Include(d => d.Tags).OrderByDescending(d => d.DataCriacao).Where(d => d.TipoAvaliacao.TipoAvaliacaoId == 3).ToList();
            carregaFiltros();
            verificaAlteraEstadoDesafio(desafios);


            return View("Index", desafios2);
        }

        public ActionResult OsMeusDesafios()
        {
            var user = User.Identity.GetUserId();
            var OsMeusDesafios = db.Desafios.Where(d => d.User.Id == user);
            return View(OsMeusDesafios.ToList<Desafio>());
        }

        private void carregaInformacaoUtilizador()
        {
            var userId = User.Identity.GetUserId();

            var utilizador = db.Users.Where(m => m.Id == userId).FirstOrDefault();
            PerfilUtilizador perfilUtilizador = new PerfilUtilizador();
            perfilUtilizador.tags = utilizador.Tags;
            perfilUtilizador.pontos = utilizador.pontos;
            perfilUtilizador.path = utilizador.ImagePath;
            ViewBag.User = perfilUtilizador;
        }

        private void carregaRecentes(IQueryable<Desafio> desafios,int count)
        {
            var numeroDesafios = 5;
            if (count < 5)
            {
                numeroDesafios = count;
            }
            ViewBag.Recentes = (from d in desafios
                                orderby d.DataCriacao descending
                                select d).Take(numeroDesafios);
        }

        private void PesquisarUtilizador(string Utilizador)
        {
            var user = db.Users.Where(m => m.UserName == Utilizador);

        }

        private void carregaFiltros()
        {
            List<SelectListItem> filtro = new List<SelectListItem>();
            filtro.Add(new SelectListItem
            {
                Text = "Recentes",
                Value = "1",
                Selected = true
            });
            filtro.Add(new SelectListItem
            {
                Text = "Mais Vistas",
                Value = "2"
            });
            filtro.Add(new SelectListItem
            {
                Text = "Valor monetário",
                Value = "3"
            });
            filtro.Add(new SelectListItem
            {
                Text = "Prazo a expirar",
                Value = "4"
            });

            ViewBag.filtro = filtro;
        }

        // GET: Desafios/Details/5
        public ActionResult Details(int? id)
        {
            var userId = User.Identity.GetUserId();
            var desafioVisualizacoes = db.Desafios.Where(d => d.DesafioId == id && d.ApplicationUserId != userId).FirstOrDefault();
            var desafio = db.Desafios.Where(d => d.DesafioId == id).First();
            var anexo = db.Anexos.Where(d => d.DesafioId == id).First();
            var Solucoes = db.Solucoes.Where(d => id == d.DesafioId).ToList();
            var diasVotacao = desafio.DiasVotacao;
            var diasAvaliacao = desafio.DiasAvaliacao + desafio.DiasVotacao;
            DateTime data = new DateTime(2016, 07, 17);
            DateTime dataFinal = desafio.DataFinalSolucoes.AddDays(diasAvaliacao + 1);
            /*if (dataFinal <= data)
            {
                Solucoes = db.Solucoes.Where(d => id == d.DesafioId).Where(m => m.Desafio.IdSolucaoVencedora != 0).ToList();
            }
            else if (desafio.DataFinalSolucoes.AddDays(diasAvaliacao) <= data)
            {
                Solucoes = db.Solucoes.Where(d => id == d.DesafioId).OrderByDescending(m => m.Estrelas.).ToList();
            }
            else if (desafio.DataFinalSolucoes.AddDays(diasVotacao) <= data)
            {
                Solucoes = db.Solucoes.Where(d => id == d.DesafioId).Where(m => m.Desafio.IdSolucaoVencedora != 0).ToList();
            }
            else if (desafio.DataFinalSolucoes < data)
            {
                Solucoes = db.Solucoes.Where(d => id == d.DesafioId).Where(m => m.Desafio.IdSolucaoVencedora != 0).ToList();
            }*/
            var user = db.Users.Where(d => d.Desafios.Any(s => s.DesafioId == id)).First();
            var tags = db.Tags
            .Where(c => c.Desafios.Any(s => s.DesafioId == id)).ToList();


            DetalhesDesafio detalhes = new DetalhesDesafio();
            detalhes.Solucoes = Solucoes;
            detalhes.TipoTrabalho = desafio.TipoTrabalho;
            detalhes.Descricao = desafio.Descricao;
            detalhes.lat = desafio.lat;
            detalhes.lon = desafio.lon;
            detalhes.FilePath = anexo.Caminho;
            detalhes.ValorMonetario = desafio.valor;
            detalhes.FileName = anexo.NomeFicheiro;
            detalhes.DataCriacao = desafio.DataCriacao;
            detalhes.FileId = anexo.AnexoId;
            detalhes.Tags = tags;
            detalhes.idUtilizador = user.Id;
            detalhes.nomeUtilizador = user.UserName;
            detalhes.DesafioId = desafio.DesafioId;
            detalhes.TipoAvaliacao = desafio.TipoAvaliacao.Descricao;
            detalhes.DataFinalAceitacao = desafio.DataFinalSolucoes;
            detalhes.diasAvaliacao = desafio.DiasAvaliacao;
            detalhes.diasVotacao = desafio.DiasVotacao;
            detalhes.Pontuacao = desafio.Pontos;


            System.Diagnostics.Debug.WriteLine(desafioVisualizacoes);
            if (desafioVisualizacoes != null)
            {
                desafioVisualizacoes.Visualizacoes++;
                db.Entry(desafioVisualizacoes).State = EntityState.Modified;
                db.SaveChanges();
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (desafio == null)
            {
                return HttpNotFound();
            }
            return View(detalhes);
        }


        private void preencherTagDesafio()
        {
            var tags = db.Tags;
            var viewModel = new List<TagDesafio>();
            foreach (var tag in tags)
            {
                viewModel.Add(new TagDesafio
                {
                    TagId = tag.Id,
                    Nome = tag.NomeTag,
                    Seleccionado = false
                });
            }
            ViewBag.TagsDesafio = viewModel;
        }

        private void preencherTagDesafio(Desafio desafio)
        {
            var tags = db.Tags;
            var tagsUsers = new HashSet<int>(desafio.Tags.Select(a => a.Id));
            var viewModel = new List<TagDesafio>();
            foreach (var tag in tags)
            {
                viewModel.Add(new TagDesafio
                {
                    TagId = tag.Id,
                    Nome = tag.NomeTag,
                    Seleccionado = tagsUsers.Contains(tag.Id)
                });
            }
            ViewBag.TagsDesafio = viewModel;
        }

        // GET: Desafios/Create

CrowdTouring Projeto/Views/Desafios/Create.cshtml
@model CrowdTouring_Projeto.ViewModel.DesafioCreate

@{
    ViewBag.Title = "Create";
}

<link rel="stylesheet" href="~/Content/tipso.min.css">
@using (Html.BeginForm("Create", "Desafios", FormMethod.Post, new {@class = "form form-horizontal", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <h3>Cria o teu desafio</h3>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group" style="margin-top:30px">
                @Html.LabelFor(m => m.TipoTrabalho, new { @class = "col-md-2 control-label" })
                <div class="col-md-10" id="pos1">
                    @Html.TextBoxFor(m => m.TipoTrabalho, new { @class = "form-control", maxlength = 50, id = "TituloDesafio", autocomplete = "off" })
                    <p id="caracteres"></p>
                </div>
            </div>
            <br />
            <div class="form-group">
                @Html.LabelFor(m => m.Descricao, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Descricao, 10, 25, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.DesafioSolucao,"Data Soluções", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.DesafioSolucao, new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(m => m.DesafioSolucao, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
        </div>
        <div class="col-md-6" style="margin-top:20px">
        <div id="map" style="width:500px; height:300px"> </div>
            </div>
    </div>
    <div class="form-group"  style="margin-right:550px">
        @Html.LabelFor(m => m.Pontos,"Pontos", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Pontos,"1",new { @class = "form-control",type = "number",min=1,max=5})
        </div>
    </div>
    <div class="form-group" style="margin-right:550px">
        @Html.LabelFor(m => m.ValorMonetario, "Valor Monetário", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ValorMonetario, new { @class = "form-control", type = "number", min = 0, max = 500 })
        </div>
    </div>
        <div class="form‐group">
        <div class="col‐md‐offset‐3 col‐md‐9"  style="margin-top:40px">
            <p>Selecciona as tuas tags preferidas</p>
            <table>
                <tr>
                    @{int cnt = 0;
                        List<CrowdTouring_Projeto.ViewModel.TagDesafio> Tags = ViewBag.TagsDesafio;
                        foreach (var tag in Tags)
                        {

                            if (cnt++ % 3 == 0)
                            {
                                @:</tr><tr>
                                }
                            @: <td style="margin-right:15px">
                                <input type="checkbox" name="selectedTag" value="@tag.TagId" checked="@tag.Seleccionado" />
                                    @tag.Nome
                                    @:</td>
                            }
                        @:</tr>
                    }
                </table>
            @Html.ValidationMessage("TagErro", new { @class = "text-danger" })
            </div>
        </div>



       @Html.HiddenFor(m => m.lat)
       @Html.HiddenFor(m => m.lon)

        <div class="form-group" style="margin-top:20px">
           <label class="col-md-offset-1">Termos de uso</label>
                <div class="col-md-10">
                     <textarea rows="8" cols="80" class="form-control" disabled>a) o "Termo" deste Contrato começa na data em que se registar na Plataforma, e continua até que seja denunciado por si ou por nós em conformidade com este Acordo;
                                                          b) declara que tem pelo menos 18 anos de idade;
                                                          c) compromete-se a não publicar conteúdos que desrespeitem outros utilizadores ou terceiros utilizando calão, palavras insultuosas, ou qualquer outro tipo situação deste género;
                                                          d) o registo e utilização da Plataforma implicam que o utilizador registado garanta que toda a informação contida no seu registo é correta.
                      </textarea>
                </div>
        </div>


        <input  type="file" name="file" class="marginTop" />     
        @Html.ValidationMessage("ErroFicheiro", new { @class = "text-danger" })
        @Html.ValidationMessage("Zip", new { @class = "text-danger" })

        
                                

        <button type="submit" class="btn btn-success marginTop" id="criarDesafio"><span class="glyphicon glyphicon-ok"></span> Criar Desafio</button>
        <br />
        <br />
                        }
    

            <script src="~/Scripts/googleMaps.js"></script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAsJgW2sXWkrM_kgAK5kF2TC2QMnHdv1G4&callback=initMap"
                    async defer></script>
            @Scripts.Render("~/bundles/jquery")
            <script>
                var text_max = 50;
                $('#caracteres').html(text_max + ' characters remaining');

                $('#TituloDesafio').keyup(function () {
                    var text_length = $('#TituloDesafio').val().length;
                    var text_remaining = text_max - text_length;

                    $('#caracteres').html(text_remaining + 'caracteres restantes ');
                });
            </script>
            <script src="~/Scripts/tipso.min.js"></script>
            <script>
                $('#TituloDesafio').tipso({
                    content: "O tipo de trabalho deverá especificar o objetivo do desafio",
                    position: "right",
                    size: "tiny"
                });

                $('#DesafioSolucao').tipso({
                    content: "Deverá indicar até que dia pretende que sejam submetidas propostas de solução num espaço de um mês",
                    position: "right",
                    size: "tiny"
                });

                $('#Descricao').tipso({
                    content: "Deverá descrever de forma detalhada o que pretende que seja feito, e deverá fazer uma descrição do seu desafio",
                    position: "right",
                    size: "tiny"
                });

                $('#Pontos').tipso({
                    content: "a pontuação varia entre 1-5 (muito fácil, fácil,normal, difícil e muito difícil respetivamente)",
                    position: "right",
                    size: "tiny"
                });

                $('#ValorMonetario').tipso({
                    content: "recompensa para o resolvedor que criar a melhor solução",
                    position: "right",
                    size: "tiny"
                });
            </script>

CrowdTouring Projeto/Views/Desafios/Index.cshtml
@model IEnumerable<CrowdTouring_Projeto.Models.Desafio>
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Index";
}

<div id="contentorAjax">
    <div class="row">
        <div class="col-md-offset-3 col-md-2">
            <h3 style="font-weight:900">Desafios</h3>
        </div>
    </div>
    <div class="row" style="margin-top:15px;margin-right:20px">
        @if (HttpContext.Current.User.IsInRole("Cliente"))
        {
            <div class="col-md-offset-3 col-md-2">
              <button class="btn btn-primary" id="CriarDesafio" onclick="@("window.location.href='" + @Url.Action("Create", "Desafios") + "'");" style="margin-left:40px">Criar desafio</button>
            </div>
        }
        @if (HttpContext.Current.User.IsInRole("Cliente"))
        {
        <div class="col-md-3">
            @using (Html.BeginForm("filtrarDesafios", "Desafios", FormMethod.Post))
            {
                @Html.DropDownList("filtro", null, new { @class = "form-control", onchange = "this.form.submit();", @style = "margin-left:20px" })
            }
        </div>
        }
        else
        {
         <div class="col-md-offset-3 col-md-3">
            @using (Html.BeginForm("filtrarDesafios", "Desafios", FormMethod.Post))
            {
                @Html.DropDownList("filtro", null, new { @class = "form-control", onchange = "this.form.submit();", @style = "margin-left:20px" })
            }
         </div>
        }
        @using (Html.BeginForm("pesquisarDesafio", "Desafios", FormMethod.Post))
        {
            <div class="input-group col-md-3" style="width:260px">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
                <input type="text" class="form-control" placeholder="Nome do desafio" name="desafio" id="srch-term">
            </div>
        }
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="row" style="border:2px solid black;border-radius:9px;margin-top:40px">
                @{
                    var utilizador = new CrowdTouring_Projeto.ViewModel.PerfilUtilizador();
                    utilizador = ViewBag.User;
                    if (utilizador.path != null)
                    {
                        <a href=@Url.Action("EditarUtilizador", "Account")><img src="~/Images/@utilizador.path" width="90" height="90" class="img-circle" style="display:block;margin-left:auto;margin-right:auto;margin-top:5px" /></a>
                    }
                    else
                    {
                        <a href=@Url.Action("EditarUtilizador", "Account")><img src="~/StaticImages/default-user-image.png" width="90" height="90" class="img-circle" style="display:block;margin-left:auto;margin-right:auto;margin-top:5px" /></a>
                    }
                    <a href=@Url.Action("EditarUtilizador", "Account")><p style="text-align:center">O meu perfil</p></a>
                    <p style="text-align:center">@utilizador.pontos</p>
                    <p style="text-align:center">Pontos</p>
                    <p style="text-align:center;font-weight:bold">Os meus interesses</p>
                    foreach (var i in utilizador.tags)
                    {
                        <ul class="tagMargin">
                            <li><a href='@Url.Action("listaDesafiosTag", "Desafios", new { id = @i.NomeTag })' name="listaTags" class="tag" style="font-size:9px;color:@i.cor">@i.NomeTag</a></li>
                        </ul>
                    }
                    <br /><br />
                    <p style="text-align:center;margin-top:20px"><a href="#">Ver Favoritos</a></p>
                    if(User.IsInRole("Cliente"))
                    {
                        <p style="text-align:center;margin-top:20px"><a href=@Url.Action("OsMeusDesafios","Desafios")>Os meus desafios</a></p>
                    }
                    using (Html.BeginForm("VisualizarPerfilUtilizador", "Account", FormMethod.Post))
                    {
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                            <input type="text" class="form-control" placeholder="Pesquisar utilizador" name="id" id="srch-term">
                        </div>
                    }

                    <br />
                    IEnumerable<CrowdTouring_Projeto.Models.Desafio> recentes = ViewBag.Recentes;
                }
            </div>
            <div class="row" style="margin-top:40px;border:2px solid black;border-radius:8px">
                <h5 style="text-align:center" class="linebef"><span>Os mais Recentes</span></h5>
                @foreach (var i in recentes)
                {
                    <div class="col-md-12">@Html.ActionLink(i.TipoTrabalho, "Details", new { id = i.DesafioId }, new { @class = "alinhaCentro" })</div>
                    <hr id="linhaRecentes" />
                }
            </div>
        </div>
        <div class="col-md-9" style="margin-top:20px">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">
                    <ul class="nav nav-tabs" style="border-bottom:1px solid gray;margin-top:15px">
                        <li id="textoAceitacaoSolucoes"><a href='@Url.Action("AceitacaoSolucoes", "Desafios")' style="font-size:10px;border-left:2px solid #d3d3d3;border-right:2px solid #d3d3d3;border-top:2px solid #d3d3d3">A aceitar soluções</a></li>
                        <li id="textoFechadoVotacao"><a href='@Url.Action("FechadoVotacao", "Desafios")' style="font-size:10px;border-left:2px solid #d3d3d3;border-right:2px solid #d3d3d3;border-top:2px solid #d3d3d3">Fechado para votação</a></li>
                        <li id="textoFechadoAvaliacao"><a href='@Url.Action("FechadoAvaliacao", "Desafios")' style="font-size:10px;border-left:2px solid #d3d3d3;border-right:2px solid #d3d3d3;border-top:2px solid #d3d3d3">Fechado para avaliação</a></li>
                    </ul>
                </legend>
                @foreach (var i in Model)
            {
                    <div class="col-md-10 secc" style="border:2px solid #669999;margin-left:5px;margin-top:5px;border-radius:8px">
                        <div class="col-md-2" style="border-right:2px solid #d3d3d3; padding-left:2px">
                            <div class="row" style="padding-top:5px">
                                <div class="col-md-6" style="text-align:center">
                                    <p class="fonteDesafio" style="font-weight:900">@i.Visualizacoes</p> <p style="font-weight:700" class="fonteDesafio">Visualizações</p>
                                </div>
                                <div class="col-md-6" style="text-align:center">
                                    <p class="fonteDesafio" style="font-weight:900">@i.Solucao.Count()</p> <p style="font-weight:700" class="fonteDesafio">Solucões</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6" style="text-align:center">
                                    <p class="fonteDesafio" style="font-weight:900">@i.Pontos</p> <p style="font-weight:700" class="fonteDesafio">Pontos</p>
                                </div>
                                <div class="col-md-6" style="text-align:center">
                                    <p class="fonteDesafio" style="font-weight:900">@i.valor€</p> <p style="font-weight:700" class="fonteDesafio">Valor</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-10">
                            <div class="col-md-12" style="margin-left:5px">
                                <a href=@Url.Action("Details", "Desafios",new {id = i.DesafioId })>
                                    <div class="col-md-12">
                                        <label style="text-decoration:underline;font-weight:900;font-size:11px">@i.TipoTrabalho</label>
                                    </div>
                                </a>
                            </div>
                            <div class="row col-md-offset-1 col-md-11" style="margin-left:15px">
                                @foreach (var tags in i.Tags)
                                {

                                    <ul class="tagMargin">
                                        <li><a href="#" class="tag" style="font-size:9px;color:@tags.cor">@tags.NomeTag</a></li>
                                    </ul>

                                }
                            </div>
                            <div class="row col-md-offset-1 col-md-11" style="margin-left:15px">
                                <div class="row seccaoDatas">
                                    <div class="col-md-8">
                                        @if (@i.User.Id == User.Identity.GetUserId())
                                        {
                                            <p style="font-weight:900" class="fonteDesafio datas">Criado por <a href=@Url.Action("EditarUtilizador", "Account")>@i.User.Nome </a>@TimeSinceEvent(@i.DataCriacao)</p>
                                        }
                                        else
                                        {
                                            <p style="font-weight:900" class="fonteDesafio datas">Criado por<a href=@Url.Action("VisualizarPerfilUtilizador","Account",new { @id = i.User.UserName})>@i.User.Nome </a>@TimeSinceEvent(@i.DataCriacao)</p>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                }
            </fieldset>
        </div>

    </div>
</div>

@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/Modal.js"></script>
<script>
    $("#textoAceitacaoSolucoes").click(function(){
        $(".textoFiltro").val() = "AceitacaoSolucoes";
    })

    $("#textoFechadoVotacao").click(function () {
        $(".textoFiltro").val() = "FechadoVotacao";
    })

    $("#textoFechadoAvaliacao").click(function () {
        $(".textoFiltro").val() = "FechadoAvaliacao";
    })
</script>
@functions{
    public static string TimeSinceEvent(DateTime eventTime)
    {
        TimeSpan timeSince = DateTime.Now - eventTime;
        if (timeSince.Days > 365)
            return string.Format("há um ano atrás");
        else if (timeSince.Days > 30)
            return string.Format("há um mês atrás");
        else if (timeSince.Days > 0)
            return string.Format("há {0} dias atrás", timeSince.Days);
        else if (timeSince.Hours > 0)
            return string.Format("há {0} horas atrás", timeSince.Hours);
        else if (timeSince.Minutes > 0)
            return string.Format("há {0} minutos atrás", timeSince.Minutes);
        else
            return string.Format("Criado á {0} segundos atrás", timeSince.Seconds);
    }
}
   


CrowdTouring Projeto/Views/Desafios/OsMeusDesafios.cshtml
@model IEnumerable<CrowdTouring_Projeto.Models.Desafio>

<h2>OsMeusDesafios</h2>

<table class="table">
<tr>
    <th>
        @Html.DisplayNameFor(model => model.TipoTrabalho)
    </th>
</tr>    

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href ='@Url.Action("Details","Desafios",new { id = item.DesafioId })'>@item.TipoTrabalho</a>
            </td>
            <td>
                @if(item.TipoAvaliacaoId == 4)
                {
                    <td>Já pode escolher vencedor!</td>
                }
            </td>
        </tr>
    }
</table>